# Generated by Django 4.2.7 on 2023-12-07 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamini +998xxxxxxxxx kabi kriting', regex='d{0,9}')])),
                ('password', models.CharField(max_length=255, null=True)),
                ('otp', models.CharField(max_length=4, null=True)),
                ('idp', models.CharField(max_length=8, null=True)),
                ('seria', models.CharField(max_length=2, null=True)),
                ('raqam', models.CharField(max_length=7, null=True)),
                ('pasport', models.FileField(blank=True, null=True, upload_to='uploads/pasports')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/image')),
                ('card', models.CharField(blank=True, max_length=4, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('addres', models.TextField()),
                ('viloyat', models.CharField(blank=True, choices=[('Toshkent', 'Toshkent'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo')], default='Toshkent', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy', models.BooleanField(blank=True, default=False, null=True)),
                ('in_basket', models.BooleanField(blank=True, default=False, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('payment', models.CharField(blank=True, choices=[('cash', 'cash'), ('credit', 'credit')], max_length=8)),
                ('period', models.IntegerField(blank=True, choices=[(3, 3), (6, 6), (12, 12)], null=True)),
                ('status', models.CharField(blank=True, choices=[('Buyurtma qabul qilindi', 'Buyurtma qabul qilindi'), ('Buyurtma bekor qilindi', 'Buyurtma bekor qilindi'), ('Buyurtma Tayorlanmoqda', 'Buyurtma Tayorlanmoqda'), ('Buyurtma Yetkazildi', 'Buyurtma Yetkazildi')], max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.users')),
            ],
        ),
    ]
