# Generated by Django 4.2.7 on 2023-11-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0004_alter_product_image'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy', models.BooleanField(blank=True, default=False, null=True)),
                ('payment', models.CharField(blank=True, choices=[('cash', 'cash'), ('credit', 'credit')], max_length=8)),
                ('period', models.IntegerField(choices=[(3, 3), (6, 6), (12, 12)])),
                ('status', models.CharField(blank=True, choices=[('Buyurtma qabul qilindi', 'Buyurtma qabul qilindi'), ('Buyurtma bekor qilindi', 'Buyurtma bekor qilindi'), ('Buyurtma Tayorlanmoqda', 'Buyurtma Tayorlanmoqda'), ('Buyurtma Yetkazildi', 'Buyurtma Yetkazildi')], max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.users')),
            ],
        ),
    ]
