# Generated by Django 4.2.7 on 2023-11-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='raqam',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
