# Generated by Django 4.2.7 on 2023-11-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='viloyat',
            field=models.CharField(blank=True, choices=[('Toshkent', 'Toshkent'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo')], default='Toshkent', max_length=30, null=True),
        ),
    ]
