# Generated by Django 4.2.7 on 2023-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='protsent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
