# Generated by Django 4.2.7 on 2023-11-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_orders_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='protsent',
        ),
    ]
