# Generated by Django 4.2.7 on 2023-12-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_orders_protsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image'),
        ),
    ]
