# Generated by Django 4.2.7 on 2023-12-07 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins', models.CharField(choices=[('Superadmin', 'Superadmin'), ('admin', 'admin')], max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=20)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamini +998xxxxxxxxx kabi kriting', regex='d{0,9}')])),
                ('password', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('Women', 'Women'), ('Man', 'Man')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('protsent', models.IntegerField(default=0)),
                ('cost', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('Elektronika', 'Elektronika'), ('Maishiy_texnika', 'Maishiy_texnika'), ('Noutbooklar', 'Noutbooklar'), ('Smartfonlar', 'Smartfonlar'), ('Planshetlar', 'Planshetlar')], max_length=250, null=True)),
                ('color', models.CharField(max_length=13, null=True)),
                ('image', models.ImageField(null=True, upload_to='uploads/rasmlar/')),
                ('time', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.admins')),
            ],
        ),
    ]
