# Generated by Django 4.2.7 on 2023-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0003_product_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/rasmlar/'),
        ),
    ]
