# Generated by Django 4.2.7 on 2023-11-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='protsent',
            field=models.IntegerField(default=0),
        ),
    ]
